site_name: Script-to-Storyboards 文档
site_description: 剧本转分镜自动化内容创作系统
use_directory_urls: true
repo_url: https://github.com/calvin-lai-0211/script-to-storyboards
repo_name: GitHub

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    # - navigation.instant  # 禁用此功能，避免 URL 跳转问题
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

nav:
  - 首页: index.md
  - API 文档:
      - 概览: api/README.md
  - 前端架构:
      - 架构说明: frontend/architecture.md
  - Docker 部署:
      - Docker 指南: DOCKER.md
  - Kubernetes:
      - 快速开始: k8s/QUICKSTART.md
      - 远程部署: k8s/REMOTE-DEPLOY.md
      - Ingress 配置: k8s/INGRESS-GUIDE.md
      - API 路由: k8s/API-ROUTING.md
      - K8s 概览: k8s/README.md
