site_name: Script-to-Storyboards 文档
site_description: 剧本转分镜自动化内容创作系统
use_directory_urls: true
repo_url: https://github.com/calvin-lai-0211/script-to-storyboards
repo_name: GitHub

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到亮色模式
  features:
    # - navigation.instant  # 禁用此功能，避免 URL 跳转问题
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search:
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

nav:
  - 首页: index.md
  - 开发指南:
      - 概览: dev/README.md
      - 快速开始: dev/getting-started.md
      - Git Hooks & CI: dev/git-hooks-and-ci.md
      - Google OAuth 认证: dev/google-oauth-authentication.md
  - 前端文档:
      - 概览: frontend/README.md
      - 快速开始: frontend/getting-started.md
      - 项目结构: frontend/project-structure.md
      - 组件设计: frontend/components.md
      - 状态管理: frontend/state-management.md
      - API 集成: frontend/api-integration.md
      - 样式指南: frontend/styling.md
      - 测试指南: frontend/testing.md
      - 代码质量: frontend/code-quality.md
      - 构建与部署: frontend/build-and-deployment.md
  - API 文档:
      - 概览: api/README.md
  - Kubernetes 部署:
      - 概览: k8s/README.md
      - 本地环境搭建: k8s/local-setup.md
      - 本地部署: k8s/local-deployment.md
      - 远程部署: k8s/remote-deployment.md
      - 运维手册: k8s/operations.md
      - 故障排查: k8s/troubleshooting.md
