apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-configmap.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml  # Ingress on port 80

# Common labels for all resources
commonLabels:
  app.kubernetes.io/name: storyboard
  app.kubernetes.io/part-of: script-to-storyboards

# Namespace (optional)
# namespace: storyboard

# Images (if using a registry)
# images:
#   - name: script-to-storyboards-api
#     newName: your-registry/script-to-storyboards-api
#     newTag: v1.0.0
#   - name: script-to-storyboards-frontend
#     newName: your-registry/script-to-storyboards-frontend
#     newTag: v1.0.0
