services:
  # Redis Service for session management
  redis:
    image: redis:7-alpine
    container_name: storyboard-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - storyboard-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  # API Service
  api:
    build:
      context: ../../
      dockerfile: docker/dockerfiles/api.Dockerfile
    image: script-to-storyboards-api:latest
    container_name: storyboard-api
    ports:
      - "8000:8000"
    environment:
      # Database will use config from utils/config.py
      # You can override with environment variables if needed
      - PYTHONUNBUFFERED=1
      - API_BASE_URL=http://localhost:8001  # 开发环境默认值
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      # Mount for development (optional - comment out for production)
      - ../../api:/app/api
      - ../../utils:/app/utils
      - ../../models:/app/models
      - ../../procedure:/app/procedure
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - storyboard-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Service
  frontend:
    build:
      context: ../../  # 改为项目根目录，以便访问 docs/ 和 mkdocs.yml
      dockerfile: docker/dockerfiles/frontend.Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL-http://localhost:8000}
    image: script-to-storyboards-frontend:latest
    container_name: storyboard-frontend
    ports:
      - "8866:80"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - storyboard-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  storyboard-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
