apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: calvin
servers: 1
agents: 0
ports:
  - port: 6443:6443
    nodeFilters:
      - "loadbalancer"
  - port: 8080:80
    nodeFilters:
      - "loadbalancer"
options:
  k3s:
    extraArgs:
      - arg: "--tls-san=127.0.0.1"
        nodeFilters:
          - "server:*"
