name: Backend Checks

on:
  push:
    branches: [ main, feat/*, fix/* ]
    paths:
      - 'api/**'
      - 'models/**'
      - 'procedure/**'
      - 'utils/**'
      - '.github/workflows/backend-checks.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
      - 'models/**'
      - 'procedure/**'
      - 'utils/**'
      - '.github/workflows/backend-checks.yml'

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true

    - name: Type check with mypy
      run: |
        mypy api/ --ignore-missing-imports || true
      continue-on-error: true

    - name: Check Python syntax
      run: |
        python -m py_compile api/**/*.py || true
      continue-on-error: true
